### ISSUE TITLE
Fix EL9 package dependencies

### ISSUE THREAD

**Issue by tillkruss** [cachewerk/linux-repos#14]
Installing Relay on EL9 works, see `el9.Dockerfile`: https://github.com/cachewerk/relay/tree/main/docker

However installing via package [(single or multi)](https://rpms.remirepo.net/wizard/) appears to be broken, or at least reference the wrong dependencies to be installed. The naming may have changed from EL8 to EL9 and needs to be updated in `config.single.el8.sh` and `config.single.el9.sh`.

**Comment by yatsukhnenko** [comment]
https://github.com/cachewerk/relay/pull/62
