### ISSUE TITLE
Add bookworm builds

### ISSUE THREAD

**Issue by tillkruss** [cachewerk/linux-repos#15]

**Comment by yatsukhnenko** [comment]
I guess bookworm is Debian 12, not a separated distro

**Comment by k0d3r1s** [comment]
will you add bookworm build?

**Comment by tillkruss** [comment]
@k0d3r1s We will publish the packages with the next release.

**Comment by k0d3r1s** [comment]
@tillkruss any ETA?

**Comment by tillkruss** [comment]
Probably after the holidays. We're just finishing up the cluster integration.

If you need a working bookworm extension now, you can install Relay using a script.

- https://github.com/cachewerk/relay/blob/main/docker/debian/debian10.Dockerfile
- https://relay.so/docs/1.x/installation#manual-installation

**Comment by k0d3r1s** [comment]
@tillkruss it is not possible to use that instruction with bookworm:  
```
ldd relay.so
	linux-vdso.so.1 (0x0000ffff93cab000)
	libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffff93b50000)
	libssl.so.1.1 => not found
	libcrypto.so.1.1 => not found
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff939a0000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffff93c6e000)
	libzstd.so.1 => /lib/aarch64-linux-gnu/libzstd.so.1 (0x0000ffff938e0000)
	liblz4.so.1 => /lib/aarch64-linux-gnu/liblz4.so.1 (0x0000ffff93890000)
	libanl.so.1 => /lib/aarch64-linux-gnu/libanl.so.1 (0x0000ffff93860000)
```

bookworm does not have `libssl.so.1.1` and `libcrypto.so.1.1`, as bookworm removed official support for openssl1

**Comment by tillkruss** [comment]
Yeah, you'll have to use the `+libssl3` artifacts.

I believe Mint 21 is identical to Bookworm:

https://github.com/cachewerk/relay/blob/main/docker/mint21.Dockerfile
