### ISSUE TITLE
Add Ubuntu 24.04 build

### ISSUE THREAD

**Issue by ghost** [cachewerk/linux-repos#19]
Hello! Could you please add a build for Ubuntu 24.04 (Noble)?

Thanks!

**Comment by tillkruss** [comment]
Have you tried using the 22.04 binary, it should work.

We'll update the apt/yum repos with the next release.

**Comment by tillkruss** [comment]
https://github.com/cachewerk/relay/commit/ad8eb5f7d97c31c7f36d375a0ace2a2b62e05d63

**Comment by tillkruss** [comment]
https://github.com/cachewerk/linux-repos/commit/25d105bc9157d9f6616a9c30eff07d457851d63c

**Comment by ghost** [comment]
Thank you! I'll give the 22.04 binary a shot.
