### ISSUE TITLE
Create `lsphp` packages

### ISSUE THREAD

**Issue by tillkruss** [cachewerk/linux-repos#6]
https://docs.litespeedtech.com/lsws/extapp/php/extensions/

```
apt install lsphpXX-relay
```

**Comment by nickchomey** [comment]
I got this error when I ran that. 

`Unable to locate package lsphp74-relay`

I already added the repo via your [apt instructions](https://relaycache.com/docs/1.x/installation#apt). 

What could the problem be?

**Comment by tillkruss** [comment]
You didn't read the title.

**Comment by nickchomey** [comment]
Oh, I'm sorry. This is you setting a task for yourself. I misunderstood

**Comment by tillkruss** [comment]
Yeah, we'll make this easier in the future with native lsphp packages.

**Comment by nickchomey** [comment]
One wrinkle - in my experience with CyberPanel and RunCloud (two of the more popular/easiest ways to use LiteSpeed) they don't really set up the php folders, symlinks etc... as expected. It could just be inherent to litespeed/lsphp. So you need to do a lot of the manual path stuff that I mentioned in #10, and seemingly in the instructions in the link you shared in the OP. Surely the existing lsphp handle this all properly as well, so could be used as a template

Hope this helps.

**Comment by nickchomey** [comment]
As a workaround for anyone who comes here later before these packages are made, you can install the normal php packages (add ondrej repo, install phpx.x, phpx.x-relay) and then symlink the .so files and copy the .ini files to their appropriate spots in the lsws directories. This allows using apt update/upgrade to stay up to date. I haven't noticed any issues yet, despite having a bunch of redundant php versions installed on the server. I'm happy to be corrected if this is, in fact, not a good idea.

**Comment by tillkruss** [comment]
@nickchomey Do you want to post a little snippet here that shows how?

**Comment by nickchomey** [comment]
This is what "worked" for me... YMMV

```
sudo apt install software-properties-common -y
sudo add-apt-repository ppa:ondrej/php -y
curl -fsSL "https://repos.r2.relay.so/key.gpg" | sudo gpg --dearmor -o "/usr/share/keyrings/cachewerk.gpg"
echo "deb [signed-by=/usr/share/keyrings/cachewerk.gpg] https://repos.r2.relay.so/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/cachewerk.list > /dev/null
sudo apt-get update
sudo apt install php7.4 php8.0 php8.1 php8.2 php7.4-{relay,xdebug} php8.0-{relay,xdebug} php8.1-{relay,xdebug} php8.2-{relay,xdebug} -y
ln -s /usr/lib/php/20210902/relay.so /usr/local/lsws/lsphp81/lib/php/20210902/relay.so
cp /etc/php/8.1/mods-available/relay.ini /usr/local/lsws/lsphp81/etc/php/8.1/mods-available/relay.ini
etc...
```


Proper lsphp packages sure would be nice though. I dont have the slightest idea of how to make them

**Comment by nickchomey** [comment]
I see that this was closed by a PR that added lsphp packages. Great! However, I don't see any instructions on how to install them in the [docs](https://relay.so/docs/1.x/installation#using-apt). 

Would it just be the same as with the normal php packages, except adding the ls prefix?

**Comment by tillkruss** [comment]
Check the readme.

**Comment by nickchomey** [comment]
Ah thanks. Probably worth adding it to the official docs though
